### ISSUE TITLE
How can I use this webapp?

### ISSUE THREAD

**Issue by beingcarrot** [pedrofracassi/amongcord-sync#1]
Hey @pedrofracassi Is this repo now directly added to the amongcord repo cuz I clicked that add amongcord to your server then what will I do

**Comment by beingcarrot** [comment]
And How can I use the webapp???

**Comment by beingcarrot** [comment]
When I open http://sync.amongcord.xyz/ then how to use it

**Comment by pedrofracassi** [comment]
The website is not working yet. It's a work in progress.

**Comment by beingcarrot** [comment]
Ok I get it

**Comment by pedrofracassi** [comment]
Should be working now. Type ,sync and it'll give you a link

**Comment by beingcarrot** [comment]
Yes got it thanx
